services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Europe/Madrid
    ports:
      - 5432:5432  # <host_port>:<container_port>

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  # <host_port>:<container_port>
